### ISSUE TITLE
Text wrap on long header broken

### ISSUE THREAD

**Issue by jacobmerson** [afeld/bootstrap-toc#13]
If there is a really long header then the text will go post the boundary of the column it is in.  E.g. on the main page:

```
<ul class="nav">
<li class=""><a href="#usage">Usage is something that we encourage because this is a really awesome plugin</a></li>
</ul>
```

Will overflow onto the body text.

I am very new to web development, so I'm not sure what the most robust way to solve this problem is. I have tracked down the issue being due to the bootstrap affix plugin.

One possible solution is to give a fixed width of the TOC in the CSS. Clearly this doesn't seem like a great general solution.

**Comment by afeld** [comment]
Hello! Sorry for the slow response. Do you have this on a live site, or would you be able to throw it in a [JSBin](http://jsbin.com/) or something to show the problem? Are you using a `float` to position the navigation bar? My guess is that the `<nav>` (or a container of it) doesn't have a `width` set in CSS – without something to restrict the width, it won't wrap.

Another thing to look at: v0.2.0 [introduced](https://github.com/afeld/bootstrap-toc/pull/14) the ability to override the text displayed for any particular heading in the nav bar:

http://afeld.github.io/bootstrap-toc/#displayed-text

Let me know if that helps or not!

**Comment by jacobmerson** [comment]
I realized that I did not have a width for the sidebar in the css. I thought that putting it inside of the col-md-4 should make the text wrap around.

Thanks for the help.

**Comment by afeld** [comment]
> I thought that putting it inside of the col-md-4 should make the text wrap around

Hmm, that _should_ be enough – you can inspect [the homepage](http://afeld.github.io/bootstrap-toc/) and [it's styles](https://github.com/afeld/bootstrap-toc/blob/gh-pages/assets/screen.css) and see that there isn't a special around the width of the column/`<nav>`. Ah well, if it works, it works!
