### ISSUE TITLE
Using JavaScript method duplicates TOC

### ISSUE THREAD

**Issue by mtaanquist** [afeld/bootstrap-toc#21]
As per subject. Using the JavaScript method would have it duplicate the TOC generated, which seemingly seems to be caused by the following code in bootstrap-toc.js:

`$(function() {
    $('nav[data-toggle="toc"]').each(function(i, el) {
      var $nav = $(el);
      Toc.init($nav);
    });
  });`

At the end of the file. It seems it adds the data-toggle to the element you choose in the function just above, and then this initialises the TOC again. Commenting it out fixed the issue for me.

**Comment by afeld** [comment]
So sorry for not getting back to you sooner. You need to make sure you don't have the `data-toggle="toc"` attribute if you are initializing the plugin via JavaScript. I made the example more clear in d08947ae6c73df9ce493546d22f25b6a1bc6c4b0. Feel free to re-open if that doesn't solve your issue!
