### ISSUE TITLE
Hash location problem with e.g. Angular 2

### ISSUE THREAD

**Issue by harryjubb** [afeld/bootstrap-toc#29]
Hi,

I'm using bootstrap-toc in an Angular 2 app, and the current method of generating the e.g. `#heading` links doesn't play nicely with the Angular 2 router.

For example, I'm using bootstrap-toc on a `domain.com/about` page, but with an `<a href="#heading">` link generated with bootstrap-toc, it navigates to `domain.com#heading`, which reloads the app, as all the Angular 2 routing is handled by Javascript.

I will submit a pull request that uses `location.href.replace(location.hash, '')` to put in the full URL, sans-existing hash, before the hash, in each generated link. I can confirm this works with Angular 2 apps, and while I can't test other types of app, I can't imagine it would cause an issue to use the full URL with the hash.

Please let me know if it is acceptable.

I would caution that this might not play nicely with single page apps using the hash location strategy for routing, but I suspect bootstrap-toc wouldn't work with these anyway.

**Comment by afeld** [comment]
Yeeeeah, I would argue that this is a bug in Angular 2, so I'm very reluctant to add any framework-specific workarounds. Does anything mentioned in these threads help?
- http://stackoverflow.com/questions/38030108/in-page-link-reloads-page
- https://github.com/angular/angular/issues/6595

**Comment by harryjubb** [comment]
That's definitely fair! Looks like it's a problem that I'll have to wait for Angular 2 to sort out. I've added the workaround to the `bootstrap-toc.js` for my app, but as I mentioned it breaks the scrollspy; the price of trying to keep up with "modern" JS..!

Thanks anyway!

**Comment by afeld** [comment]
Cool cool. Post here if there are any updates!
