### ISSUE TITLE
How to truncate some specific characters in every heading elements when generate TOC

### ISSUE THREAD

**Issue by yusiwen** [afeld/bootstrap-toc#32]
Thanks for your great work. It's easy to use and save me a lot time.

I generate my pages out of markdown files, while rendering I add some special characters (e.g. '¶', as a link to go back to top) to every heading elements (e.g. `<h1>`). So the TOC made by `bootstrap-toc` also has them. How to truncate these characters.

Thanks!

**Comment by afeld** [comment]
I would use a bit of jQuery to loop through the headings and set the [`data-toc-text`](https://afeld.github.io/bootstrap-toc/#displayed-text) attribute with the filtered text, before [initializing the plugin via JavaScript](https://afeld.github.io/bootstrap-toc/#via-javascript). Let me know if that works!
