### ISSUE TITLE
Displaying ToC without javascript suggestion

### ISSUE THREAD

**Issue by ghost** [afeld/bootstrap-toc#33]
Hello,
Thank you for a fantastic job. If you have perspectives for future development, please consider adding the possibility to display this ToC with javascript turned off (just like on bootstrap page).

**Comment by afeld** [comment]
Hey - thanks for the request. The point of the plugin is to be able to drop it in to add a table of contents on the page, regardless of where that HTML is coming from, and that's only possible with client-side JavaScript. It could add Node.js support, I suppose, but I don't really think it's worth the effort. Thanks!
