### ISSUE TITLE
Init is fired twice

### ISSUE THREAD

**Issue by peterbenoit** [afeld/bootstrap-toc#34]
I'm not sure if this is an issue with the implementation or something I'm doing.

I want to run some code prior to initializing Toc, and I want to run it after the document is ready, so it looks something like this:
```
$( function() {
    var $thing = $('#otp');
    Toc.init( $thing );
} );
```
The thing is, this creates the Toc nav which is then created again when the document ready method in your library is fired - so I'm ending up with multiple UL's in the nav creating repeating headings.

Do you have any suggestions on what I should do?

**Comment by afeld** [comment]
See https://github.com/afeld/bootstrap-toc/issues/21#issuecomment-229340655 - let me know if that doesn't do the trick!

**Comment by peterbenoit** [comment]
Just to follow up, this ended up being an order of operations issue. I called init prior to your library running its document.ready function, so the page contained a nav `data-toggle="toc"` (since your lib adds that attribute) at the time even when the default HTML markup only contained a `<nav id="toc"></nav>`.

Totally my fault, but I'm wondering if there's a way to safeguard against my error.
