### ISSUE TITLE
compatibility with Bootstrap 4?

### ISSUE THREAD

**Issue by andysmith26** [afeld/bootstrap-toc#39]
I'm trying this out on a page which uses Bootstrap 4. No luck yet: the menu aligns horizontally and it scrolls off the top of the page.

Bootstrap [mentions](https://v4-alpha.getbootstrap.com/migration/) that `affix` is no longer supported in v4. 

Do you already see any easy workarounds? (or maybe my symptoms just suggest user error?)

Thanks--

**Comment by afeld** [comment]
Ah cool, I didn't know about `position: sticky`! Started on support for Bootstrap 4 in #40.

**Comment by salcan** [comment]
Just landed on this issue as well. I'm still on v3.3.6 or whatever but as per https://v4-alpha.getbootstrap.com/migration/ the spec is moving to pos: sticky

Cool that you are on it! Awesome work.

**Comment by fredgrott** [comment]
I can get to somewhat work with bs4..ie v 0.4.1 two notes...

had to change the ul.nav display stuff which was a given considering the changes in BS4.

2nd issue...its only currently picking up h1s..not sure what that is about as there are no exception errors
