### ISSUE TITLE
Consider hosting assets at another location

### ISSUE THREAD

**Issue by fviolette** [afeld/bootstrap-toc#42]
Hello,

I have colleagues in China which can't load the CSS and JS assets from cdn.rawgit.com (`net ERR_CONNECTION_TIMED_OUT`)

Did you meet the issue before? Would it make sense to host the files at another (alternate) location?

Thanks.

**Comment by afeld** [comment]
Hmm, first I've heard of it, but that's annoying. Easiest solution is probably for the site to self-host the assets. Hope that helps!
