### ISSUE TITLE
Specify header elements to include i.e. only include <h2> in the TOC

### ISSUE THREAD

**Issue by dave-k** [afeld/bootstrap-toc#48]
Is it possible to specify which header elements to include i.e. only include "h2" in the TOC.

**Comment by lokimckay** [comment]
I don't think we currently have the ability to only include a certain heading level, however you can tell bootstrap-toc to ignore a heading with ["data-toc-skip"](https://afeld.github.io/bootstrap-toc/#skipping)

E.g.
```
<h1 data-toc-skip>Some heading you don't want in the nav</h1>
<h2>Some heading you want in the nav</h2>
```

Please explain your use case if this isn't suitable

**Comment by afeld** [comment]
Yep, doable! Use the `scope`:

```js
Toc.init({
  $scope: $('.h2')
});
```
