### ISSUE TITLE
offset function

### ISSUE THREAD

**Issue by drgrubman** [afeld/bootstrap-toc#59]
Would it be possible for the scroll to have a slight offset to accommodate for a bootstrap navbar? 

Right now it highlights something, but the heading tag is behind the navbar. If I could offset the scroll I could line it up better.

Thanks!

**Comment by afeld** [comment]
I'd say that problem is out of scope for this plugin, but thankfully it can be solved with [just a bit of CSS](https://stackoverflow.com/a/13184714/358804).

**Comment by drgrubman** [comment]
Thanks. Apologies, I'm still pretty new to building front ends. Love your tool!
