### ISSUE TITLE
I have a Bootstrap 4 Fixed Navbar - How to Offset?

### ISSUE THREAD

**Issue by jaradc** [afeld/bootstrap-toc#69]
I have a Bootstrap 4 `fixed-top` navbar.

When I click a link in bootstrap-toc, the header is hidden under the navbar.

How do I offset it a bit?

**Comment by afeld** [comment]
You're using the `.sticky-top` class, right? I think you just want to set a (larger) `top` value on the `nav`.

```html
<nav id="toc" data-toggle="toc" class="sticky-top"></nav>
```

```css
nav[data-toggle="toc"] {
  top: 42px;
}
```

**Comment by jaradc** [comment]
Nah, that wasn't it. I was asking when I click a link in the toc, not the position of the toc itself. Not sure we're saying the same thing but I found a solution.

```
// When TOC link is clicked, offset needed because fixed navbar
    $(function () {
      $('#toc .nav-link').on('click', function () {
        let hash = $(this).attr('href');
        //console.log(hash);
        $('html, body').animate({
	        scrollTop: $(hash).offset().top - 70
        }, 100)
      });
    });
```

**Comment by afeld** [comment]
Ah, gotcha. Even simpler solution:

```css
html {
  scroll-padding-top: 70px;
}
```

https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/

**Comment by jaradc** [comment]
That's awesome! Thanks for teaching me this. Also, great job on bootstrap-toc.

**Comment by reclifford** [comment]
Super helpful. Thanks!
