### ISSUE TITLE
H1 up to h6

### ISSUE THREAD

**Issue by gtbu** [afeld/bootstrap-toc#93]
H1 is a huge format. So many sites work with h5 and h6. 
What must i do to have a h5 and h6 - toc (which entries and where - Bootstrap 5)

**Comment by afeld** [comment]
[The documentation](https://afeld.github.io/bootstrap-toc/#headings) explains how it picks the top-level heading. If you'd like this to be different, you can [adjust via the `$scope` option](https://afeld.github.io/bootstrap-toc/#via-javascript).

The plugin will only display two levels, to keep the navigation from getting too cluttered. Displaying more than that is not supported (or recommended).

Hope that helps!

**Comment by gtbu** [comment]
no ::: 
 Toc.init({
  $scope: $("h4");
});
--- gives  a js-syntax-error : the toc functions but with h1

also :   opts.$nav.attr("data-toggle", "toc");    ---> $nav is undefined.. (bootstrap-toc.js 165)

**Comment by afeld** [comment]
It's a bit hard to understand what's going on without more information. Can you put together a [CodePen](https://codepen.io/) or something with a simplified example of what you're trying to do?

**Comment by gtbu** [comment]
I cant make a codepen : I added the js and css to TypesetterCMS  bootstrap5-theme ( Plesk Test) - it functions with 
  
< body data-bs-spy="scroll" data-bs-target="#toc">
 
Seitenbalken 
   < nav id="toc" class="panel" data-toggle="toc"></nav>
   
---   script.js--------
   $(function () {
  var navSelector = "#toc";
  var $myNav = $(navSelector);
  Toc.init($myNav);
 /* Toc.init({$scope: $("h4")}); */
  $("body").scrollspy({
    target: navSelector,
  });
});

Toc is not defined - in Firefox debugger if i add
Toc.init({
("h4");
});

also : opts.$nav.attr("data-toggle", "toc"); ---> $nav is undefined.. (bootstrap-toc.js 165)
- disappears if i add : if (opts && opts.$nav) { opts.$nav.attr("data-toggle", "toc");	

Uncaught SyntaxError: missing } after property list --- note: { opened at line 8, column 16
bootstrap-toc.js:172:4note: 
bootstrap-toc.js:8:16      window.Toc....

**Comment by gtbu** [comment]
well - i went back to <nav id="toc"></nav>  and

$(function () {
  var navSelector = "#toc";
  var $myNav = $(navSelector);
  Toc.init($myNav);
  $("body").scrollspy({
    target: navSelector,
  });
});
Evtl. i will take a php-version
